# Move to the treasure room and defeat all the ogres.
while True:
    hero.moveUp(4)
    hero.moveRight(4)
    hero.moveDown(3)
    hero.moveLeft()
    enemy = hero.findNearestEnemy()
    hero.attack(enemy)
    hero.attack(enemy)
    enemy2 = hero.findNearestEnemy()
    hero.attack(enemy2)
    hero.attack(enemy2)
    enemy3 = hero.findNearestEnemy()
    hero.attack(enemy3)
    hero.attack(enemy3)
    hero.moveLeft()
    enemy4 = hero.findNearestEnemy()
    hero.attack(enemy4)
    hero.attack(enemy4)